#!/usr/bin/php
<?php

use App\Controllers\AppController;
use App\Services\SchedulingService;

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

if (!isset($argv[1]) || !file_exists($argv[1])) {
    echo "Please supply a valid JSON file.\n";
    exit;
}

$json_file = $argv[1];
$json_string = file_get_contents($json_file);
if ($json_string === false) {
    echo "Error reading data from JSON file. Please try again with a valid JSON file.\n";
    exit;
}

$json_data = json_decode($json_string);

$appController = new AppController(new SchedulingService());
$appController->handle($json_data);
