#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

if (!isset($argv[1]) || !file_exists($argv[1])) {
    echo "Please supply a valid JSON file.\n";
    exit;
}

$json_file = $argv[1];
$json_string = file_get_contents($json_file);
if ($json_data === false) {
    echo "Error reading data from JSON file. Please try again with a valid JSON file.\n";
    exit;
}

$json_data = json_decode($json_string);
